### ISSUE TITLE
String in tags.

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#1247] opened 2023-07-15 14:37 UTC
We're using the numfmt npm library for tagging numbers which mimics excel and (i think) also used by LookML.

I currently have no way to write this string in a tag (that I can figure out). 

   https://malloydata.github.io/documentation/visualizations/numbers

```
# format="0 \" String\"" # Integer followed by a string (123 String)
                              #   Note \"String\" can be replaced with any other word
```

```
source: flight2 is duckdb.table('data/flights.parquet') {

  query: by_carrier is {
    aggregate: 
      # value_format="#,##0 \"miles\""
      distance is distance.sum()
  }
}
```

![image](https://github.com/malloydata/malloy/assets/1093458/3b6ec490-4bbd-4214-b8bd-635e4295e187)

**Comment by whscullin** [comment] 2023-07-19 18:24
The excel formatter used by lookml is [ssf](https://www.npmjs.com/package/ssf)

**Comment by lloydtabb** [comment] 2023-07-20 05:08
Oh s***.  Perhaps we should switch?   Sorry Fernando.  Can you take a look
and see the level of effort?

**Comment by narreola** [comment] 2023-07-20 05:41
sure I actually have a branch where I already switched to use that package but I'm seeing some weird behavior. I'm out for the rest of the week but will take a look on Monday.

**Comment by mtoy-googly-moogly** [comment] 2023-07-24 14:58
I have https://github.com/malloydata/malloy/pull/1255 as a quick fix for passing `\"` in a tag property properly

**Comment by narreola** [comment] 2023-07-24 15:23
This fix could help, with give it a try once merged. Thanks Michael.

**Comment by christopherswenson** [comment] 2023-07-24 15:24
I had an existing PR, https://github.com/malloydata/malloy/pull/1252. This also allows arbitrary escapes to be used, not just `\"`.

**Comment by christopherswenson** [comment] 2023-07-24 15:25
Sorry, thought @mtoy-googly-moogly knew I had that open, since I requested a review.

**Comment by narreola** [comment] 2023-07-24 16:57
I can confirm this is  fixed now, pushing new malloy version with the fix included.

**Closed** 2023-07-24 16:57 UTC
