### ISSUE TITLE
Handle colon in table name

### ISSUE THREAD

**Issue by bporterfield** [malloydata/malloy#249] opened 2022-01-25 02:19 UTC
<img width="620" alt="Screen Shot 2022-01-24 at 2 58 36 PM" src="https://user-images.githubusercontent.com/108260/150898573-1560132d-50bb-4b79-9f53-beea51ba7093.png">

BigQuery public datasets use colons in the table ID - a user trying to build a model on a public dataset will naturally copy the table ID, which will then fail in Malloy.

**Comment by greg-finley** [comment] 2022-04-16 07:24
Maybe this is no longer an issue? The table info and a query itself want dots:

<img width="1015" alt="Screen Shot 2022-04-16 at 12 21 59 AM" src="https://user-images.githubusercontent.com/86626072/163665923-c660608c-9000-418b-a7e0-3fdbf173fc5e.png">

Using the colon will not work:
<img width="545" alt="Screen Shot 2022-04-16 at 12 22 13 AM" src="https://user-images.githubusercontent.com/86626072/163665941-5c908053-4c0c-4aa3-89fb-324417f361e9.png">

Text of query for reference:

```sql
select count(*) from `bigquery-public-data.hacker_news.full`;
```

**Comment by lloydtabb** [comment] 2022-04-16 16:11
There are some weird cases where bigquery still accepts colons.  Keeping it open for that...

**Comment by greg-finley** [comment] 2022-04-19 22:48
Btw this is a dupe of https://github.com/looker-open-source/malloy/issues/108

**Comment by greg-finley** [comment] 2022-04-19 22:48
Btw this is a dupe of https://github.com/looker-open-source/malloy/issues/108

**Comment by carlineng** [comment] 2023-05-19 21:34
Matthew Porter just this issue: https://malloy-community.slack.com/archives/C025JAK8G0N/p1684526303832219

**Closed** 2023-05-19 22:18 UTC
Labels: language

**Comment by mtoy-googly-moogly** [comment] 2023-05-19 22:21
( closed because it is a dup )
