### ISSUE TITLE
BigQuery shouldn't change project based on table name ... or something

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [malloydata/malloy#1110] opened 2023-05-19 22:30 UTC
I think the bigquery dialect parses a table name, and uses the project in the table name in the API call. That produces this problem:

> Let's say I have Project A set as the default project to use, and I have a Malloy source defined which hits Project B.
If the query were to run in Project A but hit data in Project B as I intended it to do, then Project B would only need to grant BigQuery Data Viewer to the service account. However, this is not the case, as this error is thrown: Access Denied: Table project_b:dataset.table: User does not have permission to query table project_b:dataset.table, or perhaps it does not exist in location US.
> When I added the BigQuery Job User role to the service account, this fixes the issue and the source can be Previewed successfully. However, my understanding of that role is that is grants the SA permissions to run jobs in that project. If this is indeed the case: Is there a way to set Malloy to only run queries in a particular project while also drawing from data in other projects?

... but @carlineng , looking into this said ...

> this line looks a little suspect: https://github.com/malloydata/malloy/blob/02fa1ac7f816d6e0e72522d4bc6f8b71681d0226/packages/malloy-db-bigquery/src/bigquery_connection.ts#L337

> i think some people specify fully-qualified tablenames as project:dataset.tablename, but that line assumes project.dataset.tablename (dot instead of colon between project and dataset)

But the OP said that replacing a `:` with a `.` didn't make the error go away, which makes me think the`:` isn't the problem

**Comment by carlineng** [comment] 2023-05-23 17:44
[Link to Slack thread](https://malloy-community.slack.com/archives/C025JAK8G0N/p1684526303832219)

**Comment by carlineng** [comment] 2023-05-23 17:55
Looks like we do this when getting table schema: https://github.com/malloydata/malloy/blob/02fa1ac7f816d6e0e72522d4bc6f8b71681d0226/packages/malloy-db-bigquery/src/bigquery_connection.ts#L353-L357

If the table name has three segments, e.g., `project1.dataset.table`, we temporarily set the `project` on the BigQuery object to the project on the source table (`project1` in this example), causing the permission errors described. The user doesn't have the permissions to create jobs on `project1`, only to read data from it.

**Comment by carlineng** [comment] 2023-05-23 22:59
Original bug reporter mentioned that this might be confounded by use of Authorized Views in BigQuery, and is running more tests on their end.

**Comment by carlineng** [comment] 2023-05-24 04:07
Closing this issue. Original bug reporter said the root cause of their issue was actually because the view was in a different BQ region from the Service Account. The BQ project name thing might still be an issue, but at least in this case it's not doing any harm.

**Closed by carlineng** 2023-05-24 04:07 UTC
